<?php

/**
 * @file
 * Module file for menu_example.
 */

/**
 * Implements hook_menu().
 */

function my_menu_menu() {
    $items['my_menu'] = array(
        'title' => 'my_menu',
        'discription' => 'My_menu',
        'page callback' => '_my_menu_callback',
        'access callback' => TRUE,
        'expanded' => TRUE,
    );

    $items['my_menu/form'] = array(
        'title' => 'My Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('my_form'),
        'access callback' => TRUE,
        'file' => 'my_form.inc',
        'weight' => 100,
    );
    return $items;

}


function _my_menu_callback($content = NULL) {
    $base_content = t(
        'This is the simple test for my work!!!');
    return '<div>' . $base_content . '</div><br /><div>' . $content . '</div>';

}

/**
 * Implements hook_menu_alter.
 * Check access for forum menu item.
 */
function my_menu_menu_alter(&$items) {
    $items['my_menu']['access callback'] = '_accesscheck';
}
/**
 * Callback to disallow access for the anonymous user.
 */
function _accesscheck(){
    global $user;
    return $user->uid;
}